-- 1. Tables (Create if not exists)
create table if not exists public.pincodes (
  id bigint generated by default as identity primary key,
  pincode text not null unique,
  city text,
  district text,
  division text,
  delivery_status text default 'Delivery',
  price_ton numeric default 0,
  price_brass numeric default 0,
  price_foot numeric default 0,
  slag_basicrate numeric default 0,
  transportation_rate numeric default 0,
  unloading_charges numeric default 0,
  final_price numeric default 0,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.inquiries (
  id bigint generated by default as identity primary key,
  type text not null,
  name text not null,
  contact text not null,
  email text,
  details jsonb,
  status text default 'new',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_details jsonb not null,
  order_details jsonb not null,
  amount numeric not null,
  payment_id text,
  payment_method text not null default 'online',
  status text default 'pending',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.marketers (
  id bigint generated by default as identity primary key,
  name text not null,
  contact text not null,
  email text,
  location text,
  experience text,
  status text default 'pending',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.faqs (
  id bigint generated by default as identity primary key,
  question text not null,
  answer text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.testimonials (
  id bigint generated by default as identity primary key,
  client_name text not null,
  content text not null,
  rating integer default 5,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.counters (
  key text primary key,
  value integer default 0
);

create table if not exists public.user_roles (
  id bigint generated by default as identity primary key,
  email text not null unique,
  role text not null default 'editor', -- 'admin', 'manager', 'editor'
  status text default 'pending', -- 'pending', 'active'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);


-- 2. Insert Default Data (Conflict handling)
insert into public.counters (key, value) values
('total_customers', 100),
('orders_delivered', 0),
('pincodes_served', 10),
('marketers_onboarded', 0)
on conflict (key) do nothing;


-- 3. Enable RLS (Safe to re-run)
alter table public.pincodes enable row level security;
alter table public.inquiries enable row level security;
alter table public.orders enable row level security;
alter table public.marketers enable row level security;
alter table public.faqs enable row level security;
alter table public.testimonials enable row level security;
alter table public.counters enable row level security;
alter table public.user_roles enable row level security;


-- 4. Policies (Drop first to avoid duplication errors)

-- Pincodes
drop policy if exists "Public Read Pincodes" on public.pincodes;
create policy "Public Read Pincodes" on public.pincodes for select using (true);

drop policy if exists "Public Read All" on public.pincodes; -- cleanup old name if exists
create policy "Public Read All" on public.pincodes for select using (true);


-- FAQs
drop policy if exists "Public Read FAQs" on public.faqs;
create policy "Public Read FAQs" on public.faqs for select using (true);

-- Testimonials
drop policy if exists "Public Read Testimonials" on public.testimonials;
create policy "Public Read Testimonials" on public.testimonials for select using (true);

-- Counters
drop policy if exists "Public Read Counters" on public.counters;
create policy "Public Read Counters" on public.counters for select using (true);

-- Inquiries
drop policy if exists "Public Insert Inquiries" on public.inquiries;
create policy "Public Insert Inquiries" on public.inquiries for insert with check (true);

-- Orders
drop policy if exists "Public Insert Orders" on public.orders;
create policy "Public Insert Orders" on public.orders for insert with check (true);

-- Marketers
drop policy if exists "Public Insert Marketers" on public.marketers;
create policy "Public Insert Marketers" on public.marketers for insert with check (true);

-- User Roles
drop policy if exists "Public Read User Roles" on public.user_roles;
create policy "Public Read User Roles" on public.user_roles for select using (true);

drop policy if exists "Public Write User Roles" on public.user_roles;
create policy "Public Write User Roles" on public.user_roles for insert with check (true);

drop policy if exists "Public Delete User Roles" on public.user_roles;
create policy "Public Delete User Roles" on public.user_roles for delete using (true);
