-- 1. Tables (Create if not exists)
drop table if exists public.pincodes cascade;

create table public.pincodes (
  id bigint generated by default as identity primary key,
  city text,
  pincode text,
  delivery_status text,
  district text,
  division text,
  slag_basicrate text,
  transportation_by_truck text, -- Exact match
  unloading_charges text,
  km text,
  forty_ton_hydraulic text, -- Exact match
  thirty_ton_hydraulic text, -- Exact match
  per_km_rate text default '0', -- NEW: for dynamic pricing
  final_price text,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.inquiries (
  id bigint generated by default as identity primary key,
  type text not null,
  name text not null,
  contact text not null,
  email text,
  details jsonb,
  status text default 'new',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_details jsonb not null,
  order_details jsonb not null,
  amount numeric not null,
  payment_id text,
  payment_method text not null default 'online',
  status text default 'pending',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.marketers (
  id bigint generated by default as identity primary key,
  name text not null,
  contact text not null,
  email text,
  location text,
  experience text,
  status text default 'pending',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.faqs (
  id bigint generated by default as identity primary key,
  question text not null,
  answer text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.testimonials (
  id bigint generated by default as identity primary key,
  client_name text not null,
  content text not null,
  rating integer default 5,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.global_configs (
  key text primary key,
  value text,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Enable RLS (Safe to re-run)
alter table public.pincodes enable row level security;
alter table public.global_configs enable row level security;
alter table public.inquiries enable row level security;
-- ... other tables ...

-- Pincodes (Full Access)
drop policy if exists "Enable full access for pincodes" on public.pincodes;
create policy "Enable full access for pincodes" on public.pincodes for all using (true) with check (true);

-- Global Configs (Full Access)
drop policy if exists "Enable full access for global_configs" on public.global_configs;
create policy "Enable full access for global_configs" on public.global_configs for all using (true) with check (true);

-- FAQs (Full Access)
drop policy if exists "Enable full access for faqs" on public.faqs;
create policy "Enable full access for faqs" on public.faqs for all using (true) with check (true);

-- Testimonials (Full Access)
drop policy if exists "Enable full access for testimonials" on public.testimonials;
create policy "Enable full access for testimonials" on public.testimonials for all using (true) with check (true);

-- Counters (Full Access)
drop policy if exists "Enable full access for counters" on public.counters;
create policy "Enable full access for counters" on public.counters for all using (true) with check (true);

-- Inquiries
drop policy if exists "Enable full access for inquiries" on public.inquiries;
create policy "Enable full access for inquiries" on public.inquiries for all using (true) with check (true);

-- Orders
drop policy if exists "Enable full access for orders" on public.orders;
create policy "Enable full access for orders" on public.orders for all using (true) with check (true);

-- Marketers
drop policy if exists "Enable full access for marketers" on public.marketers;
create policy "Enable full access for marketers" on public.marketers for all using (true) with check (true);

-- User Roles
drop policy if exists "Enable full access for user_roles" on public.user_roles;
create policy "Enable full access for user_roles" on public.user_roles for all using (true) with check (true);

-- Initial Global Configs
insert into public.global_configs (key, value) values
('slag_basicrate', '0'),
('transportation_by_truck', '0'),
('unloading_charges', '0'),
('per_km_rate', '0')
on conflict (key) do nothing;
