-- FIX: Restore "user_roles" table and simplify RLS policies
-- Run this in your Supabase SQL Editor to fix the "relation public.user_roles does not exist" error.

-- 1. Restore the user_roles table if it's missing
CREATE TABLE IF NOT EXISTS public.user_roles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text NOT NULL UNIQUE,
  role text NOT NULL DEFAULT 'editor',
  status text DEFAULT 'pending',
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Clean up and simplify policies for all management tables
DO $$ 
DECLARE 
    tbl text;
    manage_tables text[] := ARRAY['inquiries', 'marketers', 'orders', 'faqs', 'testimonials', 'counters', 'user_roles', 'pincodes'];
BEGIN 
    FOREACH tbl IN ARRAY manage_tables LOOP
        -- Disable RLS temporarily to clean up
        EXECUTE format('ALTER TABLE public.%I DISABLE ROW LEVEL SECURITY', tbl);
        
        -- Drop ALL existing policies on the table to start fresh
        EXECUTE (
            SELECT COALESCE(string_agg(format('DROP POLICY %I ON public.%I', policyname, tbl), '; '), 'SELECT 1')
            FROM pg_policies 
            WHERE tablename = tbl AND schemaname = 'public'
        );

        -- A) ALLOW AUTHENTICATED USERS FULL ACCESS
        -- This covers anyone who has logged in via Supabase Auth
        EXECUTE format('CREATE POLICY "Auth_Manage_All" ON public.%I FOR ALL TO authenticated USING (true) WITH CHECK (true)', tbl);

        -- B) PUBLIC ACCESS RULES
        -- Public READ for content tables
        IF tbl IN ('faqs', 'testimonials', 'counters', 'pincodes') THEN
            EXECUTE format('CREATE POLICY "Public_Read_Only" ON public.%I FOR SELECT TO anon USING (true)', tbl);
        
        -- Public INSERT for form tables
        ELSIF tbl IN ('inquiries', 'marketers', 'orders') THEN
            EXECUTE format('CREATE POLICY "Public_Submit_Forms" ON public.%I FOR INSERT TO anon WITH CHECK (true)', tbl);
        END IF;

        -- Re-enable RLS
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', tbl);
    END LOOP;
END $$;

-- 3. Verification Message
SELECT 'Success!user_roles table restored and policies simplified.' as status;
